name: auth070
description: Authorization Library Package to log into Google, Facebook, or by Username and Password.
version: 1.1.0
author: Greg Perry <support@andrioussolutions.com>
homepage: https://github.com/AndriousSolutions/auth
repository: https://github.com/AndriousSolutions/auth

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dartlang.org/packages/firebase_auth#-changelog-tab-
  firebase_auth: 0.7.0

  # https://pub.dartlang.org/packages/google_sign_in#-changelog-tab-
  google_sign_in: 3.2.4

  # https://pub.dartlang.org/packages/http#-changelog-tab-
  http: ^0.12.0+1

  # https://pub.dartlang.org/packages/flutter_webview_plugin#-changelog-tab-
  flutter_webview_plugin: ^0.3.1

  # https://pub.dartlang.org/packages/crypto#-changelog-tab-
  crypto: ^2.0.6

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
  path_provider: ^0.4.0

  # https://pub.dartlang.org/packages/uuid#-changelog-tab-
  uuid: ^2.0.0

  # https://pub.dartlang.org/packages/prefs#-changelog-tab-
  prefs: ^1.0.0

  # https://pub.dartlang.org/packages/encrypt#-changelog-tab-
  encrypt: ^2.0.0

  # https://pub.dartlang.org/packages/device_id#-changelog-tab-
  device_id: ^0.1.3

  # https://pub.dartlang.org/packages/flutter_auth_buttons#-changelog-tab-
  flutter_auth_buttons: #^0.3.1
    git:
      url: git://github.com/Andrious/flutter_auth_buttons.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
